# Generated by Django 4.2.7 on 2023-11-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_review_user_alter_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='service',
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user1', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.customuser'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.customuser'),
        ),
    ]
