# Generated by Django 4.2.7 on 2023-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='service_images/default.png', upload_to='service_images/'),
        ),
    ]
